/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import javax.swing.JOptionPane;

/**
 *
 * @author LuisDanielCL
 */
public class VentanaMenu extends javax.swing.JFrame {

    VentanaPrincipal ventanaPrincipal;
    public VentanaMenu(VentanaPrincipal pVentanaPrincipal) {
        ventanaPrincipal = pVentanaPrincipal;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        btnPersona = new javax.swing.JMenuItem();
        btnIntereses = new javax.swing.JMenuItem();
        btnActividad = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        btnAddEvento = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Persona");

        btnPersona.setText("Registrar");
        btnPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPersonaActionPerformed(evt);
            }
        });
        jMenu1.add(btnPersona);

        btnIntereses.setText("Agregar intereses");
        btnIntereses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInteresesActionPerformed(evt);
            }
        });
        jMenu1.add(btnIntereses);

        jMenuBar1.add(jMenu1);

        btnActividad.setText("Actividades y eventos");

        jMenuItem1.setText("Registrar actividad");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        btnActividad.add(jMenuItem1);

        btnAddEvento.setText("Registrar evento");
        btnAddEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddEventoActionPerformed(evt);
            }
        });
        btnActividad.add(btnAddEvento);

        jMenuBar1.add(btnActividad);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPersonaActionPerformed
        AddPersona addPersona = new AddPersona(this);
        addPersona.setVisible(true);
        this.setEnabled(false);
    }//GEN-LAST:event_btnPersonaActionPerformed

    private void btnInteresesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInteresesActionPerformed
        AddIntereses addIntereses = new AddIntereses(this);
        addIntereses.setVisible(true);
        this.setEnabled(false);
    }//GEN-LAST:event_btnInteresesActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        JOptionPane.showInputDialog("Nombre de la actividad");
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void btnAddEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddEventoActionPerformed
        AddEvento addEvento = new AddEvento(this);
        addEvento.setVisible(true);
        this.setEnabled(false);
    }//GEN-LAST:event_btnAddEventoActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu btnActividad;
    private javax.swing.JMenuItem btnAddEvento;
    private javax.swing.JMenuItem btnIntereses;
    private javax.swing.JMenuItem btnPersona;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    // End of variables declaration//GEN-END:variables
}
