/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import Interfaz.Consultas.ConsultaDireccion;
import Interfaz.Consultas.ConsultaPersona;
import Interfaz.Consultas.ConsultaFecha;
import Interfaz.Consultas.CosultaCursoActividadEventoPorFecha;
import Interfaz.Consultas.ConsultaEmpleados;
import Interfaz.Estadisticas.EstadisticaDireccion;
import Interfaz.Estadisticas.EstadisticaIngresos;
import javax.swing.JOptionPane;

/**
 *
 * @author LuisDanielCL
 */
public class VentanaMenu extends javax.swing.JFrame {

    VentanaPrincipal ventanaPrincipal;
    public VentanaMenu(VentanaPrincipal pVentanaPrincipal) {
        ventanaPrincipal = pVentanaPrincipal;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        btnPersona = new javax.swing.JMenuItem();
        btnIntereses = new javax.swing.JMenuItem();
        btnActividad = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        btnAddEvento = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        btnRegistarCurso = new javax.swing.JMenuItem();
        btnEditar = new javax.swing.JMenuItem();
        DesercionCurso = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        btnAgregarPuestos = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        btnNacionalidad = new javax.swing.JMenuItem();
        btnPais = new javax.swing.JMenuItem();
        btnProvincia = new javax.swing.JMenuItem();
        btnCanton = new javax.swing.JMenuItem();
        btnAddDistrito = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        btnBusquedaDirecciones = new javax.swing.JMenuItem();
        jbtBusquedaPersona = new javax.swing.JMenuItem();
        btnDesercionPorCurso = new javax.swing.JMenuItem();
        btnConsultaCursosActividadesEventos = new javax.swing.JMenuItem();
        btnFiltrarEmpleado = new javax.swing.JMenuItem();
        btnTop10Ingresos = new javax.swing.JMenu();
        btnCantidadIngresos = new javax.swing.JMenuItem();
        btnBusquedaDireccion = new javax.swing.JMenuItem();
        btnCantidadEmpleados = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        btnTop5Actividades = new javax.swing.JMenuItem();
        btnTop5CursosDemanda = new javax.swing.JMenuItem();
        btnTop5Deserciones = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel4.setText("DD/MM/AAAA");
        jLabel4.setToolTipText("");

        jLabel5.setText("HH:MM am/pm");
        jLabel5.setToolTipText("");

        jTextField1.setText("Busqueda persona ID");

        jButton1.setText("Agregar");

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Persona 1, 12:20 PM , motivo", "Persona 3, 2:00 PM , motivo" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jButton2.setText("Eliminar");

        jLabel1.setText("Registro de entrada");

        jLabel6.setText("Motivo ingreso");
        jLabel6.setToolTipText("");

        jMenu1.setText("Persona");

        btnPersona.setText("Editar personas");
        btnPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPersonaActionPerformed(evt);
            }
        });
        jMenu1.add(btnPersona);

        btnIntereses.setText("Intereses");
        btnIntereses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInteresesActionPerformed(evt);
            }
        });
        jMenu1.add(btnIntereses);

        jMenuBar1.add(jMenu1);

        btnActividad.setText("Actividades y eventos");

        jMenuItem1.setText("Actividades");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        btnActividad.add(jMenuItem1);

        btnAddEvento.setText("Eventos");
        btnAddEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddEventoActionPerformed(evt);
            }
        });
        btnActividad.add(btnAddEvento);

        jMenuBar1.add(btnActividad);

        jMenu2.setText("Cursos");

        btnRegistarCurso.setText("Registrar curso");
        btnRegistarCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistarCursoActionPerformed(evt);
            }
        });
        jMenu2.add(btnRegistarCurso);

        btnEditar.setText("Editar curso");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        jMenu2.add(btnEditar);

        DesercionCurso.setText("Deserción");
        DesercionCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DesercionCursoActionPerformed(evt);
            }
        });
        jMenu2.add(DesercionCurso);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Empleados");

        jMenuItem2.setText("Editar empleados");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        btnAgregarPuestos.setText("Agregar puestos");
        btnAgregarPuestos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarPuestosActionPerformed(evt);
            }
        });
        jMenu3.add(btnAgregarPuestos);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Direcciones");

        btnNacionalidad.setText("Nacionalidad");
        btnNacionalidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNacionalidadActionPerformed(evt);
            }
        });
        jMenu4.add(btnNacionalidad);

        btnPais.setText("País");
        btnPais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPaisActionPerformed(evt);
            }
        });
        jMenu4.add(btnPais);

        btnProvincia.setText("Provincia");
        btnProvincia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProvinciaActionPerformed(evt);
            }
        });
        jMenu4.add(btnProvincia);

        btnCanton.setText("Cantón");
        btnCanton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCantonActionPerformed(evt);
            }
        });
        jMenu4.add(btnCanton);

        btnAddDistrito.setText("Distrito");
        btnAddDistrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddDistritoActionPerformed(evt);
            }
        });
        jMenu4.add(btnAddDistrito);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Consultas");

        jMenuItem3.setText("Ingreso por fechas");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem3);

        btnBusquedaDirecciones.setText("Busqueda por Dirección");
        btnBusquedaDirecciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBusquedaDireccionesActionPerformed(evt);
            }
        });
        jMenu5.add(btnBusquedaDirecciones);

        jbtBusquedaPersona.setText("Busqueda de persona");
        jbtBusquedaPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtBusquedaPersonaActionPerformed(evt);
            }
        });
        jMenu5.add(jbtBusquedaPersona);

        btnDesercionPorCurso.setText("Deserciones por curso");
        btnDesercionPorCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDesercionPorCursoActionPerformed(evt);
            }
        });
        jMenu5.add(btnDesercionPorCurso);

        btnConsultaCursosActividadesEventos.setText("Filtro: cursos, actividades y eventos");
        btnConsultaCursosActividadesEventos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultaCursosActividadesEventosActionPerformed(evt);
            }
        });
        jMenu5.add(btnConsultaCursosActividadesEventos);

        btnFiltrarEmpleado.setText("Empleado");
        btnFiltrarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltrarEmpleadoActionPerformed(evt);
            }
        });
        jMenu5.add(btnFiltrarEmpleado);

        jMenuBar1.add(jMenu5);

        btnTop10Ingresos.setText("Estadística");

        btnCantidadIngresos.setText("Cantidad de ingresos");
        btnCantidadIngresos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCantidadIngresosActionPerformed(evt);
            }
        });
        btnTop10Ingresos.add(btnCantidadIngresos);

        btnBusquedaDireccion.setText("Busqueda por dirección");
        btnBusquedaDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBusquedaDireccionActionPerformed(evt);
            }
        });
        btnTop10Ingresos.add(btnBusquedaDireccion);

        btnCantidadEmpleados.setText("Cantidad de empleados");
        btnCantidadEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCantidadEmpleadosActionPerformed(evt);
            }
        });
        btnTop10Ingresos.add(btnCantidadEmpleados);

        jMenuItem4.setText("Top 10 personas que más ingresan");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        btnTop10Ingresos.add(jMenuItem4);

        btnTop5Actividades.setText("Top 5 actividades con más demanda");
        btnTop5Actividades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTop5ActividadesActionPerformed(evt);
            }
        });
        btnTop10Ingresos.add(btnTop5Actividades);

        btnTop5CursosDemanda.setText("Top 5 cursos con más demanda");
        btnTop5CursosDemanda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTop5CursosDemandaActionPerformed(evt);
            }
        });
        btnTop10Ingresos.add(btnTop5CursosDemanda);

        btnTop5Deserciones.setText("Top 5 cursos con más deserciones");
        btnTop5Deserciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTop5DesercionesActionPerformed(evt);
            }
        });
        btnTop10Ingresos.add(btnTop5Deserciones);

        jMenuBar1.add(btnTop10Ingresos);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2))
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(35, 35, 35)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jLabel6)
                .addGap(3, 3, 3)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(21, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPersonaActionPerformed
        AddPersona addPersona = new AddPersona(this);
        addPersona.setVisible(true);
        this.setEnabled(false);
    }//GEN-LAST:event_btnPersonaActionPerformed

    private void btnInteresesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInteresesActionPerformed
        AddIntereses addIntereses = new AddIntereses(this);
        addIntereses.setVisible(true);
        this.setEnabled(false);
    }//GEN-LAST:event_btnInteresesActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        AddActividad addActividad = new AddActividad(this);
        addActividad.setVisible(true);
        this.setEnabled(false);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void btnAddEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddEventoActionPerformed
        AddEvento addEvento = new AddEvento(this);
        addEvento.setVisible(true);
        this.setEnabled(false);
    }//GEN-LAST:event_btnAddEventoActionPerformed

    private void btnRegistarCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistarCursoActionPerformed
        AddCurso addCurso = new AddCurso(this);
        addCurso.setVisible(true);
        this.setEnabled(false);
    }//GEN-LAST:event_btnRegistarCursoActionPerformed

    private void DesercionCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DesercionCursoActionPerformed
        SelectCurso selectCurso = new SelectCurso(this, "desercion");
        selectCurso.setVisible(true);
        this.setEnabled(false);
    }//GEN-LAST:event_DesercionCursoActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        AddEmpleado addEmpleado = new AddEmpleado(this);
        addEmpleado.setVisible(true);
        this.setEnabled(false);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        SelectCurso selectCurso = new SelectCurso(this, "editarCurso");
        selectCurso.setVisible(true);
        this.setEnabled(false);
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnAgregarPuestosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarPuestosActionPerformed
        AddPuestos addPuestos = new AddPuestos(this);
        addPuestos.setVisible(true);
        this.setEnabled(false);
    }//GEN-LAST:event_btnAgregarPuestosActionPerformed

    private void btnNacionalidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNacionalidadActionPerformed
        AddNacionalidad addNacionalidad = new AddNacionalidad(this);
        addNacionalidad.setVisible(true);
        this.setEnabled(false);
    }//GEN-LAST:event_btnNacionalidadActionPerformed

    private void btnPaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPaisActionPerformed
        AddPais addPais = new AddPais(this);
        addPais.setVisible(true);
        this.setEnabled(false);
    }//GEN-LAST:event_btnPaisActionPerformed

    private void btnProvinciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProvinciaActionPerformed
        AddProvincia addProvincia = new AddProvincia(this);
        addProvincia.setVisible(true);
        this.setEnabled(false);
    }//GEN-LAST:event_btnProvinciaActionPerformed

    private void btnCantonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCantonActionPerformed
        AddCanton addCanton = new AddCanton(this);
        addCanton.setVisible(true);
        this.setEnabled(false);
    }//GEN-LAST:event_btnCantonActionPerformed

    private void btnAddDistritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddDistritoActionPerformed
        AddDistrito addDistrito = new AddDistrito(this);
        addDistrito.setVisible(true);
        this.setEnabled(false);
    }//GEN-LAST:event_btnAddDistritoActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        ConsultaFecha consultaFecha = new ConsultaFecha(this);
        consultaFecha.setVisible(true);
        this.setEnabled(false);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void btnBusquedaDireccionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBusquedaDireccionesActionPerformed
        ConsultaDireccion consultaDireccion = new ConsultaDireccion(this);
        consultaDireccion.setVisible(true);
        this.setEnabled(false);
    }//GEN-LAST:event_btnBusquedaDireccionesActionPerformed

    private void jbtBusquedaPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtBusquedaPersonaActionPerformed
        ConsultaPersona consultaPersona = new ConsultaPersona(this);
        consultaPersona.setVisible(true);
        this.setEnabled(false);
    }//GEN-LAST:event_jbtBusquedaPersonaActionPerformed

    private void btnDesercionPorCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDesercionPorCursoActionPerformed
        SelectCurso selectCurso = new SelectCurso(this, "desercionCurso");
        selectCurso.setVisible(true);
        this.setEnabled(false);
    }//GEN-LAST:event_btnDesercionPorCursoActionPerformed

    private void btnConsultaCursosActividadesEventosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultaCursosActividadesEventosActionPerformed
        CosultaCursoActividadEventoPorFecha consultaPorFecha = new CosultaCursoActividadEventoPorFecha(this);
        consultaPorFecha.setVisible(true);
        this.setEnabled(false);
    }//GEN-LAST:event_btnConsultaCursosActividadesEventosActionPerformed

    private void btnFiltrarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltrarEmpleadoActionPerformed
        ConsultaEmpleados consultaEmpleado = new ConsultaEmpleados(this);
        consultaEmpleado.setVisible(true);
        this.setEnabled(false);
    }//GEN-LAST:event_btnFiltrarEmpleadoActionPerformed

    private void btnCantidadIngresosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCantidadIngresosActionPerformed
        EstadisticaIngresos estadisticaIngresos = new EstadisticaIngresos(this);
        estadisticaIngresos.setVisible(true);
        this.setEnabled(false);
    }//GEN-LAST:event_btnCantidadIngresosActionPerformed

    private void btnBusquedaDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBusquedaDireccionActionPerformed
        EstadisticaDireccion estadisticaDireccion = new EstadisticaDireccion(this);
        estadisticaDireccion.setVisible(true);
        this.setEnabled(false);
    }//GEN-LAST:event_btnBusquedaDireccionActionPerformed

    private void btnCantidadEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCantidadEmpleadosActionPerformed
        JOptionPane.showMessageDialog(rootPane, "La cantidad de empleados es: 000");
    }//GEN-LAST:event_btnCantidadEmpleadosActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        JOptionPane.showMessageDialog(rootPane, "Las personas que más ingresan son:"
                + "\nPersona 1"
                + "\nPersona 3"
                +"\nPersona 2"
                +"\nPersona 4");
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void btnTop5ActividadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTop5ActividadesActionPerformed
                JOptionPane.showMessageDialog(rootPane, "Las actividades con más demanda son:"
                + "\nActividad 1"
                + "\nActividad 3"
                +"\nActividad 2"
                +"\nActividad 4");
    }//GEN-LAST:event_btnTop5ActividadesActionPerformed

    private void btnTop5CursosDemandaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTop5CursosDemandaActionPerformed
                JOptionPane.showMessageDialog(rootPane, "Los cursos con más demanda son:"
                + "\nCursos 1"
                + "\nCursos 3"
                +"\nCursos 2"
                +"\nCursos 4");
    }//GEN-LAST:event_btnTop5CursosDemandaActionPerformed

    private void btnTop5DesercionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTop5DesercionesActionPerformed
                JOptionPane.showMessageDialog(rootPane, "Los cursos con más deserción son:"
                + "\nCursos 4"
                + "\nCursos 2"
                +"\nCursos 3"
                +"\nCursos 1");
    }//GEN-LAST:event_btnTop5DesercionesActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem DesercionCurso;
    private javax.swing.JMenu btnActividad;
    private javax.swing.JMenuItem btnAddDistrito;
    private javax.swing.JMenuItem btnAddEvento;
    private javax.swing.JMenuItem btnAgregarPuestos;
    private javax.swing.JMenuItem btnBusquedaDireccion;
    private javax.swing.JMenuItem btnBusquedaDirecciones;
    private javax.swing.JMenuItem btnCantidadEmpleados;
    private javax.swing.JMenuItem btnCantidadIngresos;
    private javax.swing.JMenuItem btnCanton;
    private javax.swing.JMenuItem btnConsultaCursosActividadesEventos;
    private javax.swing.JMenuItem btnDesercionPorCurso;
    private javax.swing.JMenuItem btnEditar;
    private javax.swing.JMenuItem btnFiltrarEmpleado;
    private javax.swing.JMenuItem btnIntereses;
    private javax.swing.JMenuItem btnNacionalidad;
    private javax.swing.JMenuItem btnPais;
    private javax.swing.JMenuItem btnPersona;
    private javax.swing.JMenuItem btnProvincia;
    private javax.swing.JMenuItem btnRegistarCurso;
    private javax.swing.JMenu btnTop10Ingresos;
    private javax.swing.JMenuItem btnTop5Actividades;
    private javax.swing.JMenuItem btnTop5CursosDemanda;
    private javax.swing.JMenuItem btnTop5Deserciones;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JList jList1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JMenuItem jbtBusquedaPersona;
    // End of variables declaration//GEN-END:variables
}
